/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeleradiologyServicesRouteImport } from './routes/teleradiology-services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ModesOfIntegrationRouteImport } from './routes/modes-of-integration'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TeleradiologyServicesRoute = TeleradiologyServicesRouteImport.update({
  id: '/teleradiology-services',
  path: '/teleradiology-services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesOfIntegrationRoute = ModesOfIntegrationRouteImport.update({
  id: '/modes-of-integration',
  path: '/modes-of-integration',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/evidence': typeof EvidenceRoute
  '/modes-of-integration': typeof ModesOfIntegrationRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/teleradiology-services': typeof TeleradiologyServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/evidence': typeof EvidenceRoute
  '/modes-of-integration': typeof ModesOfIntegrationRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/teleradiology-services': typeof TeleradiologyServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/evidence': typeof EvidenceRoute
  '/modes-of-integration': typeof ModesOfIntegrationRoute
  '/products': typeof ProductsRoute
  '/research': typeof ResearchRoute
  '/resources': typeof ResourcesRoute
  '/solutions': typeof SolutionsRoute
  '/teleradiology-services': typeof TeleradiologyServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/evidence'
    | '/modes-of-integration'
    | '/products'
    | '/research'
    | '/resources'
    | '/solutions'
    | '/teleradiology-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/evidence'
    | '/modes-of-integration'
    | '/products'
    | '/research'
    | '/resources'
    | '/solutions'
    | '/teleradiology-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/evidence'
    | '/modes-of-integration'
    | '/products'
    | '/research'
    | '/resources'
    | '/solutions'
    | '/teleradiology-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EvidenceRoute: typeof EvidenceRoute
  ModesOfIntegrationRoute: typeof ModesOfIntegrationRoute
  ProductsRoute: typeof ProductsRoute
  ResearchRoute: typeof ResearchRoute
  ResourcesRoute: typeof ResourcesRoute
  SolutionsRoute: typeof SolutionsRoute
  TeleradiologyServicesRoute: typeof TeleradiologyServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teleradiology-services': {
      id: '/teleradiology-services'
      path: '/teleradiology-services'
      fullPath: '/teleradiology-services'
      preLoaderRoute: typeof TeleradiologyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes-of-integration': {
      id: '/modes-of-integration'
      path: '/modes-of-integration'
      fullPath: '/modes-of-integration'
      preLoaderRoute: typeof ModesOfIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EvidenceRoute: EvidenceRoute,
  ModesOfIntegrationRoute: ModesOfIntegrationRoute,
  ProductsRoute: ProductsRoute,
  ResearchRoute: ResearchRoute,
  ResourcesRoute: ResourcesRoute,
  SolutionsRoute: SolutionsRoute,
  TeleradiologyServicesRoute: TeleradiologyServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
